language: node_js
node_js:
- '11.6'
branches:
  only:
  - master
before_script:
- npm install
- npm install -g firebase-tools
script:
- ng build @helvio/angular-inline-edit
- ng build --prod
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
notifications:
  email:
    on_failure: change
    on_success: change
before_deploy:
- cd dist/helvio/angular-inline-edit
deploy:
  provider: npm
  skip_cleanup: true
  email: helvio88@gmail.com
  api_key:
    secure: heE629et7hru1FTfoTPHJT4gTgx+aXoL0K3FkJT9nAiyeNgf/MaIt/vnxS/i7dYP6XjynaCLLAodL0eL5bSdVAwrY6+A+Uw4fAjCjgKjSOgj3R+oUdae+aneWViLjKEAO7W4JCdugpC4Jke/dyJrOJcezs1ELO+OG9AT3IxqnHltM56x+qPFFJpDbRFLxvmKjFyibXdXD17uqLSW7Tv+8ebDR/WNxICaZBNDJ2zWx/xiUsGlhvlrtq3S25XvQw8hwATenQ5dxEmNoV56LBzjs9KNAX0LnVoJsMb7gLrlFp4XSJp+MqorXqf8BSN8+5AsfXjlUGzKzknRMXnTMvoz/eEJapS5ltSx+VlGjV3T8ErdvLd21RYXdoAJOxPuvxVXUUxUoGJ7ef8UaXSmjxfOlAk1P7j+Ek2xkJko5GRONKqIdjUvTKwMjAMQUxx4fvVSNfOnSo+YwlAY4YDcHBiy/hrnWnogt7UYPrupR2VAiZ4Q7xqAFPW2bb002xDhdSa77zc0kIDrXbbp6U8XN9lmas4j6i90RrHYlvpeNEp8FXKRi6gGLeYnq4Y9d6g5M6cbvQm1+BtY5DF7UMaeDRAfFoTSp60gQBrZcadOSAmvuuF6QrPME/00Q3JwIElAy5Ld5c1tJIN9V4avQTUcY+fUQ4nRfXi45tEeUKZplKZsNJU=
  on:
    all_branches: true
    repo: Helvio88/angular-inline
